export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST";
export const FETCH_ARTICLE_LIST_SUCCESS = "FETCH_ARTICLE_LIST_SUCCESS";
export const FETCH_ARTICLE_LIST_FAIL = "FETCH_ARTICLE_LIST_FAIL";
export const SET_SELECTED_ARTICLE = "SET_SELECTED_ARTICLE";